### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by asimaranov** [OliverHaag/rust-inkview#1]
I want to use your bindings in my rust pocketbook game. Please add a license so I can do this

**Comment by OliverHaag** [comment]
Added the license information, was missing since this is in a rather early stage at the moment.

I've also pushed my latest changes, I can also provide a small example project using the bindings if you wish?

**Comment by asimaranov** [comment]
![image](https://user-images.githubusercontent.com/25568730/99253464-dbb47280-2821-11eb-8bac-ae0eae57e346.png)
No, thanks, I have already walked through this, and made a simple port of a text game. I will publish the game in open source as soon as I finish it
